# Generated by Django 5.1.6 on 2025-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
